- name: "Config folder"
  ansible.builtin.file:
    path: "{{ ansible_user_dir }}/.config/tmux"
    state: directory

- name: "Copy tmux.conf"
  ansible.builtin.copy:
    src: "tmux.conf"
    dest: "{{ ansible_user_dir }}/.config/tmux/tmux.conf"
