- name: Update all packages to their latest version
  ansible.builtin.apt:
    name: "*"
    state: latest
    cache_valid_time: 3600

- name: Upgrade the OS (apt-get dist-upgrade)
  ansible.builtin.apt:
    upgrade: dist
