- name: Update and upgrade the system
  include_tasks: "{{ ansible_os_family }}.yml"

- name: Install packages (fish, git, tmux, bat, unzip, ripgrep, wget) 
  ansible.builtin.package:
    name:
      - fish
      - git
      - tmux
      - bat
      - unzip
      - ripgrep
      - wget
    state: present

- name: Make local bin dir
  become: false
  ansible.builtin.file:
    path: "{{ ansible_user_dir }}/.local/bin"
    state: directory

- name: "Copy tmux-sessionizer script to local bin"
  become: false
  ansible.builtin.copy:
    src: "{{ role_path }}/files/tmux-sessionizer"
    dest: "{{ ansible_user_dir }}/.local/bin/tmux-sessionizer"
    mode: '700'

