- name: Update and upgrade the system
  include_tasks: "{{ ansible_os_family }}.yml"

- name: Install Zsh
  ansible.builtin.package:
    name: zsh
    state: present

- name: Install Git
  ansible.builtin.package:
    name: git
    state: present

- name: Install Tmux
  ansible.builtin.package:
    name: tmux
    state: present

- name: Install Bat
  ansible.builtin.package:
    name: bat
    state: present

- name: Install Unzip
  ansible.builtin.package:
    name: unzip
    state: present

- name: Install Ripgrep
  ansible.builtin.package:
    name: ripgrep
    state: present

- name: Install Wget
  ansible.builtin.package:
    name: wget
    state: present

- name: Make local bin dir
  become: false
  ansible.builtin.file:
    path: "{{ ansible_user_dir }}/.local/bin"
    state: directory

- name: "Create symlink to tmux-sessionizer"
  become: false
  ansible.builtin.file:
    src: "{{ role_path }}/files/tmux-sessionizer"
    dest: "{{ ansible_user_dir }}/.local/bin/tmux-sessionizer"
    state: link
    mode: 700

