- name: "Create symlink to starship.toml"
  ansible.builtin.file:
    src: "{{ role_path }}/files/starship.toml"
    dest: "{{ ansible_user_dir }}/.config/starship.toml"
    state: link
    force: true
