- name: "Config folder"
  ansible.builtin.file:
    path: "{{ ansible_user_dir }}/.config/nvim"
    state: directory

- name: "Create symlink to role files directory"
  ansible.builtin.file:
    src: "{{ role_path }}/files"
    dest: "{{ ansible_user_dir }}/.config/nvim"
    state: link
    force: true
